name: 02-workflow-events
on:
#   push:
  pull_request:
#   schedule:
#     - cron: '*/5 * * * *' # runs every day at midnight
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: show the triggering event
        run: |
            echo "The event that triggered this workflow is: ${{ github.event_name }}"